.github/workflows/ci.yml, package.json
=> lint in ci

src/pages/Home.vue
=> [Done] Rename 'Longer List' to 'Inbox' #162

src/components/LongerList.vue, src/components/molecules/Cards/ItemCard.vue
=> [Done] DRAFT: Do not allow text to bleed into LONG LIST #124

src/components/atoms/SlotTitleInput.vue, src/pages/Home.vue
=> [Done] Ability to hide a pane/column #142

src/components/organisms/AppBar.vue, src/store/longListItems.ts, src/store/podcasts.ts
=> [Done] make data/podcasts a store #144

src/layouts/authenticated.vue, src/pages/Home.vue
=> [Done] Make each pane scroll individually #137

src/hooks/routes/auth.ts, src/routes/index.ts, src/store/auth.ts
=> [Done] ALL: Remember User Login #176

src/components/LongerList.vue, src/components/molecules/Cards/ItemCard.vue
=> [Done] INBOX: Truncate URL links to 50chars #169

src/components/LongerList.vue, src/pages/Home.vue, src/store/longListItems.ts
=> [Done] DRAFT: Change order of items to newest > oldest #205

src/pages/Home.vue
=> [Done] ALL: accordian movement for pane/column #126

package-lock.json, package.json
Reverts DaftDoris/newsdesk#274
=> Revert "Update dependency vue-tsc to v0.36.0"

cypress/e2e/podcasts.cy.js, src/components/molecules/Cards/ItemCard.vue
=> used dynamic position in clientX and clientY

cypress/e2e/podcasts.cy.js, src/components/Script.vue, src/components/organisms/AppBar.vue, src/pages/Home.vue
=> Create 7 sections in script

cypress/e2e/podcasts.cy.js, src/pages/Home.vue
=> resolved bug

cypress/e2e/podcasts.cy.js, src/pages/Home.vue
=> remove dark out in inbox and draft

cypress/e2e/podcasts.cy.js, src/components/Script.vue, src/components/atoms/ClipField.vue
In this request, I've made the changes in 2 files
1. scripts.vue in which I added delete function defination and 
2. clipfield.vue in which I've added delete button and pass data through props and emit delete function also.
=> SCRIPT 4a: Ability to DELETE a CLIP field #372

src/components/Script.vue, src/pages/Home.vue, src/store/item.ts
In this PR, we've made the significant changes to the structure of data saving of script section in firestore, please check attached image below. 
Now the data of script will change when we change the data like draft.
=> SCRIPT: Does not update when selecting date #488

src/components/Script.vue, src/store/item.ts
The unique id of the clips was not working as expected we used the index of the item to delete the clip field
=> BUG: Deleting one clip field deletes all of them

src/components/Inbox.vue, src/components/Script.vue, src/components/molecules/Cards/ItemCard.vue, src/pages/Home.vue
All text and icon are styled according to the dark theme as well. Also added comments in the code to remeber at dark theme styling.
=> BUG: make sure all vue icons and text have dark mode versions #529

src/pages/Home.vue
Change the jspdf library to accept html tags.
=> BUG: PDF displaying HTML tags

src/pages/Home.vue
The updated code do not contains the delete function to be called when dragging items from draft to script
=> REVERSION: Apologies - we no longer wish for DRAFT to DELETE
